use_frameworks!

platform :ios, '8.0'

target 'XKURLProtocol_Example' do
  pod 'XKURLProtocol', :path => '../'

  target 'XKURLProtocol_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
